### ISSUE TITLE
Do not allow `revdep_add()` with packages that are not revdeps

### ISSUE THREAD

**Issue by jimhester** [r-lib/revdepcheck#109]
I accidently used `revdep_add()` to add a package with a misspelled name, which caused a number of problems downstream because the package did not actually exist and was not a reverse dependency.

I think the easiest solution is just to throw an error if you try to add a package which is not a reverse dependency.

**Comment by HenrikBengtsson** [comment]
Though, `revdep_add(packages = ...)` provides a way to test also (some or all of the) _recursively_ dependent packages, which otherwise cannot be tested (Issue #69).
