### ISSUE TITLE
Master too slow for many (e.g. 80) workers

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/revdepcheck#117]
We need to write stdout and stderr to files, instead of reading them out continuously.

**Comment by gaborcsardi** [comment]
CC @krlmlr

**Comment by jimhester** [comment]
That doesn't seem right to me, there isn't that much raw output, even from 24 or 80 workers, what is being saturated?

**Comment by gaborcsardi** [comment]
Well, that's basically the only thing the master is doing, so it must be that.

**Comment by jimhester** [comment]
I bet it is the explicit `gc()` that is the issue

https://github.com/r-lib/revdepcheck/blob/ee1843ef1de51de3ae6ab69ec85ed0910f05f075/R/event-loop.R#L69

I realize you need to do an explicit gc periodically to clean up the file handles, but doing it every iteration means you are essentially gcing continuously.

**Comment by jimhester** [comment]
I think you can just gc after each task is done?

**Comment by gaborcsardi** [comment]
That's actually a pretty good guess, and the gc call is not needed with the new processx version. @krlmlr can you please try to remove the `gc()` and run it again with many workers?

**Comment by krlmlr** [comment]
Now running without `gc()` and with detailed debugging info for each step of the event loop.

**Comment by jimhester** [comment]
I ran profvis on `revdep::revdep_check(num_workers = 20)` for the 21 glue dependencies. Since profvis only profiles the current R process this should measure just what the master thread is doing.

Anyway most of the time seems to be spent doing `gc()`, and a lot of other time is spent calling `available.packages()`. I don't know crancache code, but `download.packages()` seems to be called with `available = NULL`, which means AFAIK it calls `available.packages()`every time internally.

https://github.com/r-lib/crancache/blob/11e6bde59e05b76b8dcabb194f693592e31d93f3/R/download-packages.R#L38

![screenshot 2017-11-08 16 23 15](https://user-images.githubusercontent.com/205275/32575275-8aa9082e-c4a1-11e7-8c59-32e704e3a58d.png)

You can play with the profvis output at https://rawgit.com/jimhester/provis-reports/master/revdepcheck-1/index.html (the files are kind of big, so be patient loading the page).

**Comment by krlmlr** [comment]
Could it be that termination of workers somehow isn't detected correctly? I'm seeing with `pstree`:

```
bash(2471)───R(31906)─┬─sh(96662)───R(96666)───sh(99880)───R(99881)
                      ├─sh(96790)───R(96794)───sh(99901)───R(99902)
                      ├─sh(97018)───R(97022)
                      └─sh(97339)───R(97343)
```

but processx claims (according to my logging output) that 24 processes are mostly silent on stdin and stdout. I have a worker timeout of one hour.

Ubuntu 16.04.

**Comment by krlmlr** [comment]
I agree that `gc()` slows down the event loop, but only the polling frequency.

**Comment by gaborcsardi** [comment]
@jimhester Thanks, that's useful! Some `available.packages()` calls are inevitable with `crancache` unfortunately, because it is transparent for the base R functions, but these calls should not go online.

@krlmlr Re `pstree` output, maybe these are just stuck? Can you look at the check log files?

**Comment by gaborcsardi** [comment]
@jimhester But these `available.packages` calls are indeed suspicious.

**Comment by krlmlr** [comment]
Not anymore for these packages, maybe for the next round. But 22 out of 24 stuck? Strikes me unlikely.

**Comment by krlmlr** [comment]
I'm grepping `00check.log` for `"^Status"` and show all files that don't have such a line (`-L`, `--files-without-match`). Only eight packages aren't finished yet, this aligns with `pstree` and `ps -elf | grep R` output.

How can I check if `processx` works as expected on my system? Would the tests indicate such a failure?

**Comment by gaborcsardi** [comment]
> I'm grepping 00check.log for "^Status" and show all files that don't have such a line (-L, --files-without-match). Only eight packages aren't finished yet, this aligns with pstree and ps -elf | grep R output.

So this is good, right?

**Comment by krlmlr** [comment]
To me this means that we have 24 - 8 = 16 worker objects that correspond to finished processes but are detected as silent.

**Comment by krlmlr** [comment]
FWIW, I'm aborting and installing the CRAN version of processx now for the tests. Happy to do more debugging.

**Comment by krlmlr** [comment]
Result: Much slower event loop (maybe due to `available.packages()` calls?), but much better turnaround. Scheduling a test task takes longest, the console usually hangs at output similar to:

```
revdepcheck scheduling +1ms 
revdepcheck +-schedule next task +1ms 
revdepcheck +-schedule checking fedreporter with the new version +1ms 
revdepcheck doing +1ms 
revdepcheck +-do a check task: fedreporter +1ms revdepcheck +-do a check task: new +1ms 
revdepcheck   +-Checking fedreporter +1ms 
```

**Comment by krlmlr** [comment]
No, that's `crancache::download_packages()` in `check_proc()`. I wonder if this should be done in a worker instead, this pauses the event loop for ~8 seconds.

**Comment by gaborcsardi** [comment]
Yes, but that just means that new tasks are not started for 8 seconds. The workers are still running happily (unless they generate a lot of output). So I would guess that this is not such a big deal.

**Comment by krlmlr** [comment]
On 64 cores this means that a check worker that is finished in less than 64 * 8 seconds, or 8 minutes, can't be occupied immediately (on average). That's a big waste. On 16 cores that's still 2 minutes, many packages require less time for their checks.

**Comment by krlmlr** [comment]
I no longer think that massive output is the reason for the problems we're seeing. R CMD check output is just a few 100 lines if at all, looks like the master process can handle this.

**Comment by gaborcsardi** [comment]
@krlmlr Yeah, but the install output can be long. Anyway, Jim's measurements are convincing.

**Comment by gaborcsardi** [comment]
So there are three issues here:
- polling in the new `processx` is broken
- download should happen in a worker
- need to check on the `available.packages` calls

Is there anything else?

**Comment by krlmlr** [comment]
The `available.package()` calls come from `crancache::download_packages()`, should be auto-fixed if the workers do the download. OTOH, if we manage to scrap these calls, maybe we don't even need to move downloading to a worker just yet?

![screenshot from 2017-11-09 10-07-19](https://user-images.githubusercontent.com/1741643/32597073-ca67b700-c535-11e7-8be5-b6ec35ec80f7.png)

**Comment by gaborcsardi** [comment]
With the current `crancache` implementation, we cannot completely avoid `available.packages`. `crancache` uses a local repo, and `utils` does not cache local repos in memory, so (unless there is a bug) `available.packages` just reads in the `PACKAGES*` file of the local repo, and yes, this is taking time.

Eventually we need a better cache. `crancache` is cumbersome, because it tries to stay fully compatible with `install.packages` etc. But in `revdepcheck` we already look up all dependencies manually, so we don't actually need `install.packages` to do any magic, we would just use it to install a local package. (And use `pkginstall`, eventually.)

For now, I think 
- making sure that `available.packages` does not have a bug, and 
- moving the download to a worker
will solve this problem.

**Comment by gaborcsardi** [comment]
OK, I think we can close this now. 

@krlmlr please reopen or open another issue if it is still slow.

**Comment by gaborcsardi** [comment]
I also got rid of the `gc()` call, if the `processx` version is new enough, btw.
