### ISSUE TITLE
Download packages in a worker

### ISSUE THREAD

**Issue by krlmlr** [r-lib/revdepcheck#118]
Otherwise the event loop is stalled by ~8 seconds for each download, this starts to matter for 16 cores or more.

Reference: https://github.com/r-lib/revdepcheck/issues/117#issuecomment-342991160

**Comment by HenrikBengtsson** [comment]
Are you suggesting to download/populate the local CRAN cache in parallel?  If so, is `crancache` really parallel safe?  (Sorry if I misunderstood)

**Comment by gaborcsardi** [comment]
`crancache` is already used in parallel, when the revdeps install their own dependencies. 

It should be fine in parallel, in general. It has no locking, but has eventual consistency. (Well, assuming atomicity of `file.copy`, which is not strictly too, but should be fine for the current purposes.)

This issue is about downloading the source package for the actual revdep. I assumed that this would be relatively fast, so it can be done by the master, but apparently, I was wrong.

**Comment by gaborcsardi** [comment]
Wow, we were already downloading it in a worker, actually, but the download was buggy. Anyway, should be good now.

**Comment by krlmlr** [comment]
Thanks. Still a few calls to `available_packages()` left -- maybe use memoise to shave off these 2x 3 seconds per downstream package (=4 hours master time for testthat)?

**Comment by HenrikBengtsson** [comment]
@gaborcsardi, regarding parallel crancache; could this be why I'm observering:
```
Warning in file.rename(file.path(dir, pkgs_new), file.path(dir, pkgs)) :
  cannot rename file '/netapp/home/hb/.cache/R-crancache/bioc-bin/src/contrib/PACKAGES.new' to '/netapp/home/hb/.cache/R-crancache/bioc-bin/src/contrib/PACKAGES', reason 'No such file or directory'
Warning in file.rename(file.path(dir, pkgs_new), file.path(dir, pkgs)) :
  cannot rename file '/netapp/home/hb/.cache/R-crancache/bioc-bin/src/contrib/PACKAGES.gz.new' to '/netapp/home/hb/.cache/R-crancache/bioc-bin/src/contrib/PACKAGES.gz', reason 'No such file or directory'
Warning in file.rename(file.path(dir, pkgs_new), file.path(dir, pkgs)) :
  cannot rename file '/netapp/home/hb/.cache/R-crancache/bioc-bin/src/contrib/PACKAGES.rds.new' to '/netapp/home/hb/.cache/R-crancache/bioc-bin/src/contrib/PACKAGES.rds', reason 'No such file or directory'
```
at times when running in parallel?

BTW, one step up from assuming atomicity of `file.copy` would be to use `file.copy` to temporary name and then rely on near-atomicity of `file.rename`.  A `atomic.file.copy` function.

**Comment by gaborcsardi** [comment]
Yes, the warnings are harmless. I'll fix them today or tomorrow.

**Comment by gaborcsardi** [comment]
OK, if you install the new `cranlike` package from `r-hub/cranlike`, the warnings go away.
