### ISSUE TITLE
feature request: revdep_skip() ?

### ISSUE THREAD

**Issue by bbolker** [r-lib/revdepcheck#123]
As a way around the problems described in https://github.com/r-lib/revdepcheck/issues/87 , and more broadly for dealing with packages that are problematic in some as-yet-unforeseen way, it would be nice if there were a `revdep_skip()` that did the opposite of `revdep_add()`, i.e. denoted a set of packages to ignore when checking.

Sorry if a way to do this already exists and I've missed it.

**Comment by HenrikBengtsson** [comment]
I second this feature request. I have a "problematic" package that tries to download 0.5 GB when checked - so I'd like to have the option to skip a package.

For now, is there a low-level DB hack to achieve the same?

**Comment by gaborcsardi** [comment]
There is revdep_rm(), is that good?

**Comment by HenrikBengtsson** [comment]
Ah... I was looking around for something `revdepcheck:::revdep_...` but couldn't find anything.  I incorrectly assumed that revdepcheck was on CRAN and I had an up-to-date version.  Just updated from an old revdepcheck 1.0.0.9000 (2018-08-12@ee4ca3a) to revdepcheck 1.0.0.9001 (2019-04-19@c317ca7) and how I see:

```r
> revdepcheck::revdep_rm
function (pkg = ".", packages) 
{
    pkg <- pkg_check(pkg)
    db_todo_rm(pkg, packages)
    invisible(revdep_todo(pkg))
}
```

Thanks. I guess this issue can be closed now.
