### ISSUE TITLE
Forget to close db connection?

### ISSUE THREAD

**Issue by jeroen** [r-lib/revdepcheck#130]
Seeing a bunch of these. 

<img width="955" alt="screen shot 2017-12-17 at 1 37 21 pm" src="https://user-images.githubusercontent.com/216319/34079521-9ac4ce6c-e32f-11e7-99bc-b380a0c7abd9.png">

**Comment by gaborcsardi** [comment]
I think this has been fixed in `cranlike` / `revdepcheck`. Please reopen if not.
