### ISSUE TITLE
`options(warnPartialMatchArgs = TRUE)` prevents revdep checks

### ISSUE THREAD

**Issue by jennybc** [r-lib/revdepcheck#134]
I have this in `.Rprofile`:

``` r
options(
  warnPartialMatchAttr = TRUE,
  warnPartialMatchDollar = TRUE,
  warnPartialMatchArgs = TRUE
)
```

which seems good for daily life and development. But it's fatal to revdepchecks. I get:

``` r
Error in rep.default(as.POSIXct(NA), length = length(dates)) : 
  (converted from warning) partial argument match of 'length' to 'length.out'
```

Feels like my `.Rprofile` shouldn't be used here.

**Comment by jennybc** [comment]
I see this is also #97 and https://github.com/gaborcsardi/parsedate/pull/22.

**Comment by hadley** [comment]
I have this set too, and I'm not seeing any problems now.
