### ISSUE TITLE
Default to displaying only new problems

### ISSUE THREAD

**Issue by hadley** [r-lib/revdepcheck#135]
This should probably be an option, but I'm finding the current rendering annoying because there's no easy way to navigate through all the new problems and in order to identify common causes.

**Comment by gaborcsardi** [comment]
So, what if one or both of the checks were timed out? And what if one or both failed to install? Should we show these?

**Comment by hadley** [comment]
I think we should show new problems - i.e. show a time out or install failure only if it occurs with the new version.

**Comment by gaborcsardi** [comment]
Should only show new problems.

**Comment by lionel-** [comment]
With this change, `revdep_email("broken")` sends mails to packages that have timed out. I'm not sure if this was intentional, I was expecting that timed out packages would get the `"failed"` email template (assuming that it is rare that a package about to be released causes infloops).
