### ISSUE TITLE
Avoid WARNING noise: "Insufficient package version" and "This build time stamp is over a month old."

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/revdepcheck#136]
Is there a way to _not_ report on the following WARNINGs?
```
Maintainer: ‘Alice Aliceson <alice@example.org>’

Insufficient package version (submitted: 0.8.0, existing: 0.8.0)

This build time stamp is over a month old.
```

They're often the only reason why a package end up in `problems.md`.

**Comment by gaborcsardi** [comment]
I have never seen these. Are you running the checks with `--as-cran`? (Is that even possible?)

**Comment by HenrikBengtsson** [comment]
Examples:
* https://github.com/HenrikBengtsson/globals/blob/develop/revdep/problems.md
* https://github.com/HenrikBengtsson/listenv/blob/b8ef00e3666060531a56a0eb8ef86b2dc0fc45d1/revdep/problems.md
* https://github.com/HenrikBengtsson/R.rsp/blob/develop/revdep/problems.md

I guess I need to start digging in to my local settings to see where this could be coming from - itäs certainly not from the `revdep_check()` call itself.

**Comment by gaborcsardi** [comment]
Yeah, I would think that omitting `--as-cran` is better for revdep checks.

**Comment by HenrikBengtsson** [comment]
First, I completely removed my `~/.Renviron` and `~/.Rprofile` and can confirm that they are in play when running revdepcheck, e.g. they used to tweak the `LANG` env variable and [the change is reflected in the revdepcheck output](https://github.com/HenrikBengtsson/listenv/commit/dbeebd1c9803cedbfc8d427b22e0f5e39fdcb39e#diff-1890a66bd55e1dc6bab18e8ff5c17ce5).

However, [those WARNINGs in my top comment still shows up also after a `revdep_reset()` and rerun](https://github.com/HenrikBengtsson/listenv/blob/ec54d6171deca87d5be9377c17ad19894bf77539/revdep/problems.md).  I've confirmed that the internal `revdep/checks/<pkg>/new/<pkg>.Rcheck/00check.log` also report on these and that the checks are truly rerun (new timestamps).

I've confirmed that `export | grep R_` is empty, i.e. I don't set any of those elsewhere in my shell.  I've also confirmed that `revdepcheck`, `rcmdcheck`, `callr`, and `processx` are all recent installs from GitHub (as reported by `packageDescription()`).

I'm puzzled.

**Comment by HenrikBengtsson** [comment]
**SOLVED**: And as always, there's a simple explanation.  I forgot that I had a `~/.R/check.Renviron` file which I was playing around with in the fall and there I was setting `_R_CHECK_CRAN_INCOMING_=true`.  Removing that, [removes those WARNINGs](https://github.com/HenrikBengtsson/listenv/commit/07431759730363c43972a82e430c25a6bbee3c6a).

Imagine if `R CMD check` to report on what files it imports and give a detailed session info log with all relevant settings. Would helped here but also on trying to reproduce CRAN checks.  Oh well, ...

**Comment by HenrikBengtsson** [comment]
A follow up here in case others get these "CRAN incoming" NOTEs:  It turns out that `revdepcheck::revdep_check()` will run `R CMD check` affected by environment variables you:

1. set in `~/.R/check.Renviron` (or in a file pointed to `R_CHECK_ENVIRON`),
2. set in `.Renviron`, or
3. set via `.Rprofile`, e.g. `Sys.setenv("_R_CHECK_CRAN_INCOMING_" = "TRUE")` or `readRenviron("some-Renviron-file")`.
