### ISSUE TITLE
Error in read.dcf(file = tmpf) when using revdep_check()

### ISSUE THREAD

**Issue by benjaminhlina** [r-lib/revdepcheck#150]
See this [SO](https://stackoverflow.com/questions/46365317/what-is-the-most-user-friendly-way-to-test-the-reverse-dependencies-for-a-packag#) thread posted September of 2017. I'm experience the same issue. I have a Windows machine and am running the newest version of R (v3.5.0) and RStudio (v1.1.453). 
Any suggestions would be helpful. Thanks

**Comment by gaborcsardi** [comment]
revdepcheck does not work currently  on windows, this  is a known issue.
