### ISSUE TITLE
HTML escaping of R-crancache results in incorrect directory

### ISSUE THREAD

**Issue by wch** [r-lib/revdepcheck#156]
On my computer, I've set up `~/Library/Caches/R-crancache` so that it is a symlink to `/Volumes/External T5/R-crancache`. When I try to run `revdep_check()`, it says that there's `no such file or directory`, but the instead of a space, there's a `%20`, which indicates that it has been HTML-escaped.

```
> revdep_check()
── CHECK ──────────────────────────────────────────────────────── 43 packages ──
Error in read.dcf(file = tmpf) : cannot open the connection
In addition: Warning message:
In read.dcf(file = tmpf) :
  cannot open compressed file '/Volumes/External%20T5/R-crancache/cran/src/contrib/PACKAGES', probable reason 'No such file or directory'

Enter a frame number, or 0 to exit   

 1: revdep_check(, num_workers = 3)
 2: revdep_run(pkg, quiet = quiet, timeout = timeout, num_workers = num_workers
 3: run_event_loop(state)
 4: do_task(state, task)
 5: deps_install_task(state, task)
 6: deps_install_opts(pkgdir, pkgname, quiet = state$options$quiet)
 7: deps_opts(pkgname, exclude = pkg_name(pkgdir))
 8: cran_deps(pkgname, repos)
 9: available_packages(repos = repos)
10: eval(call, envir = parent.frame())
11: eval(call, envir = parent.frame())
12: utils::available.packages(repos = c(cran = "file:///Volumes/External%20T5/R
13: read.dcf(file = tmpf)

Selection:
```

I know that it's non common to have a space (or other character that requires HTML escaping) in the path to the cache, but I needed to do it because I'm running out of disk space.

**Comment by hadley** [comment]
Given that no one else has reported this, I think we can close. You (specifically) can now use #247 if you need to check a bunch of packages.
