### ISSUE TITLE
revdep_check() should add revdep/ to .Rbuildignore

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/revdepcheck#177]
tl;dr - Currently, `revdep_check()` creates a `revdep/` folder, but does not add that folder to `.Rbuildignore`.

I ran revdeps for the first time on a package right before submitting to CRAN. All was well, so I shipped it. I may or may not have accidentally shipped the entire `revdep/` folder with the package. 😈 This issue should prevent that from happening to others.

**Comment by gaborcsardi** [comment]
`usethis::use_revdep()` adds it already. It is not revdepcheck's business to do this.
