### ISSUE TITLE
Show a little more package metadata in problems.md

### ISSUE THREAD

**Issue by hadley** [r-lib/revdepcheck#182]
It would be nice to have:

* the BugReports url (to make it easier to file an issue on GitHub)
* the total number of dependencies (so that when you have multiple packages failing because of the same underlying cause, you can pick a package with few dependencies to debug)

**Comment by gaborcsardi** [comment]
This is somewhat challenging, because adding more columns to the tables will not take us very far... anyway, I can certainly add these two, and then we'll see.

**Comment by hadley** [comment]
Oh, I didn't mean in the table, I meant underneath the package name heading.

**Comment by gaborcsardi** [comment]
Oh, right, problems.md, not in the README. Got it.

**Comment by gaborcsardi** [comment]
This is easier after I switch to pkgcache. Then all this info will be readily available. #187

**Comment by gaborcsardi** [comment]
OTOH, switching to pkgcache would make sense if we switch to pkgdepends/pkginstall as well, to install packages, so I'll not wait for that.

**Comment by hadley** [comment]
It would also be useful to include (e.g) `revdep_details(,"platetools")` as a prompt of how to get more info
