### ISSUE TITLE
Practical advice on usage

### ISSUE THREAD

**Issue by jennybc** [r-lib/revdepcheck#186]
I'd like to record what I did most recently. Maybe it would be helpful to give advice somewhere? Or you can close this issue and I can re-search it up when I need it 😁

I think this is basically good advice and it mattered a lot trying to do revdep checks in a place with incredibly bad internet.

Run R in the shell, as opposed to an/the instance of RStudio open to the target package. In general, suppress your personal startup behaviour.

I needed to keep my computer awake for loooooong periods of time so I also used the macOS caffeinate feature:

```
caffeinate -i R --vanilla
```

In R, I used `.libPaths("path/to/my/library/for/non-base-or-recommended-packages")` to add my personal library to the search path, so I could use revdepcheck.

In general, do this:
``` r
revdep_check(num_workers = 4)
```

If there are problem packages that keep timing out and holding on to a worker (I see this is now fixed #183), note their names. Kill the job. Explicitly remove the problem packages like so:

``` r
revdepcheck:::revdep_rm(".", c("BIOMASS", "cartools", "rstantools"))
```

Restart with multiple workers. When things stall, note more problem packages. Lather, rinse, repeat until you get through the bulk of the job.

Now tackle the problem packages one at a time with a really long timeout.

``` r
revdepcheck::revdep_add(".", "BIOMASS")
revdep_check(pkg = ".", quiet = FALSE, timeout = as.difftime(60, units = "mins"))
```

**Comment by hadley** [comment]
Should this go here or in r-pkgs?

**Comment by gaborcsardi** [comment]
Since #183 is fixed, I think most of this will not come up again.
