### ISSUE TITLE
Installation error status

### ISSUE THREAD

**Issue by schloerke** [r-lib/revdepcheck#190]
While checking, installation errors are not showing the red "I" like they use to.

Adding installation error packages with `revdepcheck::revdep_add_broken(install_failures = TRUE)` does not add the packages.

Installation errors are not printed in problems.md by default.  (This may be changed behavior though.  If it is, they should not have a dead link from the `README.md` file.)

My current status information:
```r
revdepcheck:::report_revdeps("shiny")$status %>% unique()
#> [1] "+"  "i+"
```

All pkgs with the status value of `i+` are the pkgs with installation failure.

Please let me know if I can provide any more information.

**Comment by schloerke** [comment]
I think this is also leaking into the output for `revdep_report_cran` status (`NA` values).

```r
revdepcheck::revdep_report_cran("shiny")
```
```
## revdepcheck results

We checked 670 reverse dependencies (577 from CRAN + 93 from BioConductor), comparing R CMD check results across CRAN and dev versions of this package.

 * We saw 0 new problems
 * We failed to check 5 packages

Issues with CRAN packages are summarised below.

### Failed to check

* BETS       (NA)
* blorr      (NA)
* EventStudy (NA)
* JMbayes    (NA)
* RQuantLib  (NA)
```

**Comment by gaborcsardi** [comment]
These parts were recently updated, so hopefully this is fixed now. Please reopen or open another issue if not.
