### ISSUE TITLE
A revdep that never times out

### ISSUE THREAD

**Issue by jennybc** [r-lib/revdepcheck#197]
I reran usethis's revdep checks over night. This is about a 30 minute job. One particular package is problematic (BIOMASS) and it sits on a worker and never goes anywhere, never times out. Here's what the end of the run looked like in the morning:

<img width="734" alt="Screen Shot 2019-04-05 at 8 20 33 AM" src="https://user-images.githubusercontent.com/599454/55638400-eec51c80-577b-11e9-9677-8ea3459f8829.png">

I've rerun the checks several times over the past few weeks and this behaviour with this package is consistent. So whatever way it hangs or fails is somehow beyond the reach of what revdepcheck does to kill things.

**Comment by jennybc** [comment]
Also when I interrupt the revdep check, I see this:

```
Warning message:
call dbDisconnect() when finished working with a connection 
```

**Comment by gaborcsardi** [comment]
Unfortunately I cannot reproduce this. BIOMASS does seem to have some race conditions, both of its check processes are using the very same file, and this sometimes reports an error, but they both finish quite quickly, nevertheless.

Please reopen if you see this again, then I'll try harder to reproduce.
