### ISSUE TITLE
Checking revdeps of R

### ISSUE THREAD

**Issue by lionel-** [r-lib/revdepcheck#207]
Before submitting a patch to R core, it's sometimes needed to check for issues against CRAN packages (all of CRAN or just a sufficiently large sample, depending on the patch).

It might be possible to check old and new R simultaneously, but it is probably hard to make this work portably.

Alternatively, the packages could be checked on old R first and then on new R. Then it's up to the user to change the currently active R version between the checks. As discussed in #198, this needs one library per checked package to ensure nothing changes between old and new checks. Or perhaps installing all deps first would work, as discussed in #33.

**Comment by hadley** [comment]
I think this is now like to be out of scope for revdepcheck.
