### ISSUE TITLE
revdep_check() fails to install packages

### ISSUE THREAD

**Issue by robjhyndman** [r-lib/revdepcheck#217]
I get dozens of errors such as this:

```
Error: package or namespace load failed for ‘tseries’:
     package ‘quadprog’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
    Execution halted
```
If I reinstall quadprog the error is not fixed.

Running R 3.6.1 on Ubuntu 18.04 with all packages updated to latest CRAN releases.

**Comment by gaborcsardi** [comment]
Possibly the cache has binaries from older R versions. Try running `crancache::crancache_clean()`.
