### ISSUE TITLE
Failing on rstudio.cloud

### ISSUE THREAD

**Issue by jimhester** [r-lib/revdepcheck#220]
I am not entirely sure why this fails, but when I try using revdepcheck on rstudio.cloud it ends up hanging. I tried running revdeps for `pkgbuild` and for `bench` in the last few days and both of them ran into problems when installing one or more packages.

It is possible that compiling certain reverse dependencies is running into the memory limits, in which case this wouldn't really be something we could fix in the package

**Comment by hadley** [comment]
Closing for now, but feel to re-open if it happens again and you get more details.
