### ISSUE TITLE
Failure of source("https://install-github.me/r-lib/revdepcheck")

### ISSUE THREAD

**Issue by nashjc** [r-lib/revdepcheck#228]
As requested by Gabor, I'm opening an issue.

I got the following output when I tried to install revdepcheck using the "source" method suggested.
I'm running Linux Mint 18.3 64 bit. Output follows.

R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> source("https://install-github.me/r-lib/revdepcheck")
Downloading GitHub repo r-lib/revdepcheck@master
Error in vapply(remote, function(x) remote_sha(x), character(1),
USE.NAMES = FALSE) :
  values must be length 1,
 but FUN(X[[1]]) result is length 98
> q()

**Comment by nashjc** [comment]
Today tried with newly set up Linux Mint Tricia 19.3 (using mintupgrade gave a login screen that kept returning to the login screen!). Install worked OK. WIll report later if package functions OK. Machine still being set up, as I had to do a bare metal install.

**Comment by hadley** [comment]
We've now moved away from that install method.
