### ISSUE TITLE
Screen continues updating after R is sent to background

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/revdepcheck#229]
Not sure if this is the right location....

I'm running a long-running check in a Linux VM, using the terminal rather than RStudio. I put it to sleep with Ctrl-Z, and then sent it to the background with `bg`. After doing this, the screen continues printing updates from `revdep_check`.

Here's a screenshot while running `top`:

![image](https://user-images.githubusercontent.com/11328890/72946429-08028c80-3dd3-11ea-8e0c-ab26f5a894d7.png)

**Comment by gaborcsardi** [comment]
That's just how terminals work.

![bg](https://user-images.githubusercontent.com/660288/73011225-bcb8a000-3e0b-11ea-8a18-cd22a2d5c24c.gif)

**Comment by Hong-Revo** [comment]
Well, you learn something new every day. 😅
