### ISSUE TITLE
Include successful revdeps in the README report somewhere

### ISSUE THREAD

**Issue by colearendt** [r-lib/revdepcheck#238]
Use case: ran revdeps successfully locally, and then one fails on CRAN.

It would be nice to have a record of successful revdeps in the README / reports somewhere as a record of the revdep process having been executed and the results being successful. It would also provide the added benefit of being able to sanity check quickly what issues, if any, were seen locally.

**Comment by gaborcsardi** [comment]
All the results are in a database, that you can look at later, either by generating the report, or using `revdep_summary()`, `revdep_details()`, etc.

**Comment by colearendt** [comment]
Thanks! Yes, `revdep_details()` is gold. Would you be amenable to a `revdep_success()` function that generates a `success.md` or something like that? My concern was mostly for publicity w/o having to commit / track the database.

**Comment by hadley** [comment]
I think our assumption is that if it didn't fail or break, it succeeded. But maybe we could include a list of all successful packages (space delimited) at the bottom of the README?

**Comment by hadley** [comment]
Actually we already have a way to do this: call `revdep_report_summary(all = TRUE)`
