### ISSUE TITLE
how to install revdepcheck?

### ISSUE THREAD

**Issue by dankelley** [r-lib/revdepcheck#261]
**Preamble.** I am preparing to submit an update to one of my CRAN packages, and so am doing the usual checks in winbuilder, rhub, etc.  And now I am at the stage of checking reverse dependencies, but I can no longer use `revdepcheck` as I had done in the past.  I'd appreciate some advice, since I feel that the actions undertaken by `revdepcheck` are very valuable.

**My issue.** The README says to install `revdepcheck` with
```R
install.packages("revdepcheck")
```
but when I try that, I get
```R
Installing package into ‘/Users/kelley/Library/R/4.0/library’
(as ‘lib’ is unspecified)
Warning message:
package ‘revdepcheck’ is not available (for R version 4.0.0)
```
so I wonder whether I ought to use `install_github()` and report those results in my CRAN comments, or whether there is a new replacement for the `revdepcheck` package, perhaps?

**Comment by ms609** [comment]
`revdepcheck` is not yet available on CRAN, as hinted in `README.md`.

Until it is, `install_github` is indeed a good way to install the package.

**Comment by dankelley** [comment]
Thanks.  I installed that way, and it works a charm.  I'll close this issue now, with my appreciation.
