### ISSUE TITLE
Works for RSQLite?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/revdepcheck#3]
I'm having trouble revdep-checking the current dev version of RSQLite with devtools. I'd like to check both CRAN and Bioconductor packages.

Do you think it's worthwhile to try revdepcheck on this project already?

**Comment by hadley** [comment]
It's working for me now (for at least dbplyr, tidyr, and purrr) so I think you should try it the next time you need to do revdeps. I'm going to use it instead of devtools from now on.

**Comment by gaborcsardi** [comment]
I just came here to close this issue. :)
