### ISSUE TITLE
Option to run with --as-cran

### ISSUE THREAD

**Issue by hadley** [r-lib/revdepcheck#31]
And default it to TRUE?

**Comment by gaborcsardi** [comment]
I am not sure if we need this. E.g. it will warn for the version number every time. (Although we can work around that.)

It will also download the package metadata, to check if the version number is bigger than on CRAN. We would need to monkey patch this I assume. Or make sure that it goes to crancache.

Also, my feeling is that the extra checks that come with `--as-cran` are not so relevant when revdep-checking. 

I think we might come back to it later, but I would not worry about this currently. 

CRAN is not doing it either, AFAIK, when revdep-checking: https://github.com/wch/r-source/blob/trunk/src/library/tools/R/checktools.R

**Comment by hadley** [comment]
I already proactively prevented the version number/metadata issue by setting the right env vars 😉 

But if CRAN isn't using it for revdeps checks, there doesn't seem to be any reason for us to either.

**Comment by gaborcsardi** [comment]
Oh, actually, about the aspell env var. I believe that is only active if you also specify `--as-cran`. So we don't need that either, I think. We probably don't want to spell check the DESCRIPTION of the revdep packages, anyway.

**Comment by hadley** [comment]
Oops yes.
