### ISSUE TITLE
Update cloud_check() to use 4.1.1 by default as the service does 

### ISSUE THREAD

**Issue by cderv** [r-lib/revdepcheck#316]
Recently, 4.1.1 has been made available and is the default on the cloud service. 

However, `cloud_check()` still set 4.0.3 by default. 

Running `revdepcheck::cloud_check(r_version = "4.1.1")` obviously works but it seems ok to upgrade the default now and avoid those type of errors 
```
1: package ‘phangorn’ is not available for this version of R
‘phangorn’ version 2.8.0 is in the repositories but depends on R (>= 4.1.0)
````

**Comment by romainfrancois** [comment]
I second that, I've seen some package fail because they start to use the triangle pipe `|>`
