### ISSUE TITLE
possible error (relates to stderr() not being a pipe)

### ISSUE THREAD

**Issue by dankelley** [r-lib/revdepcheck#322]
Hello.  I am trying to do `revdep_check` on the `oce` package, in preparation for a CRAN submission (which is necessitated because oce relies on Rcpp, and the latter is due for a CRAN update next week, which will break oce).

I see as below the line of dashes.  I'm not too sure whether this means that there is a problem with the `argoFloats` package, the `oce` package, or with `revdep_check` itself.  I wonder whether anybody could advise me on what to try next.

Both `oce` and `argoFloats` are big packages, and I'm not asking anyone to look into the details of the problem, if it indeed rests in those packages.  What I am hoping, however, is that someone might give me a hint as to how I can find out what's wrong in what I'm doing.  

Thanks in advance, for anyone who can provide some guidance.

PS.  a `git grep stderr` within `argoFloats` produces no results.  The same is true for `oce`.

---------

```
> revdepcheck::revdep_check()
── INIT ───────────────────────────────────────────── Computing revdeps ──
── INSTALL ───────────────────────────────────────────────── 2 versions ──
Installing CRAN version of oce
Installing DEV version of oce
── CHECK ────────────────────────────────────────────────── 10 packages ──
[0/10] 00:00:25 | ETA:  ?s | (1) argoFloats [C_]Error in process_get_error_connection(self, private) : 
  stderr is not a pipe.
Type .Last.error.trace to see where the error occurred
> traceback()
10: stop(cond)
9: throw(new_error("stderr is not a pipe."))
8: process_get_error_connection(self, private)
7: process_read_error(self, private, n)
6: proc$read_error(n = 10000)
5: handle_event(state, i)
4: handle_events(state, events)
3: run_event_loop(state)
2: revdep_run(pkg, quiet = quiet, timeout = timeout, num_workers = num_workers, 
       env = env)
1: revdepcheck::revdep_check()
```

**Comment by gaborcsardi** [comment]
Try updating all dependencies of revdepcheck:
```
pak::pkg_install("r-lib/revdepcheck", upgrade = TRUE)
```

**Comment by dankelley** [comment]
Thanks very much.  All works fine now, so I'll close the issue.
