### ISSUE TITLE
Running revdep_check for one dependency at a time

### ISSUE THREAD

**Issue by MarkEdmondson1234** [r-lib/revdepcheck#326]
Hello, I would like to run each package dependency check in parallel across Google Cloud Build, and am trying it out with `googleAuthR` with 18 dependencies.

I would like to loop over the package dependencies and then check them one at a time, but can't find a way to do that with `revdep_check()` that only gives options for the types of package ("Suggest", etc)

Is there a way to first list all the dependencies (without running `revdep_check()` first) and then check only one package?  Perhaps exporting some of the internal functions?

**Comment by gaborcsardi** [comment]
revdepcheck is probably not the right tool for this. Fwiw 18 revdeps will finish on an average laptop quite quickly, with the default 10 minute time limit, if you have at least 4 processors.

**Comment by MarkEdmondson1234** [comment]
Ok fair enough, it does finish quick enough in a single build too. Thanks!
