### ISSUE TITLE
Installation instructions don't work

### ISSUE THREAD

**Issue by lbergelson** [r-lib/revdepcheck#336]
I inherited the maintenance of an R package and ended up here through the [Hadley Wickham book](https://r-pkgs.org/release.html#release-deps)

I tried following the [installation instructions](https://github.com/r-lib/revdepcheck/blob/main/README.md#installation) in the README but they don't work because the package doesn't seem to be on CRAN.

How are you supposed to install this package?

**Comment by lbergelson** [comment]
I opened a PR to avoid future confusion.

**Comment by lbergelson** [comment]
It uses the information I found here: https://github.com/r-lib/revdepcheck/issues/261

**Comment by gaborcsardi** [comment]
I removed the installation instructions of dev versions from all my packages, so people prefer the cran versions and don't mess up their package libraries with experimental packages.

**Comment by hadley** [comment]
But revdepcheck isn't on CRAN, so we should probably restore the github instructions.
