### ISSUE TITLE
revdep folder should be added to buildignore

### ISSUE THREAD

**Issue by ColinFay** [r-lib/revdepcheck#351]
Launching the `revdepcheck::revdep_check(num_workers = 4)` function will create a folder at the root of the package called `revdep`. 

This folder is not added to the buildignore, so following the worflow from `usethis::use_release_issue` makes the submitted package fail, because we do the checks before the revdeps, but if not buildignored, the CRAN submission fails. 

```
 + [ ] devtools::check(remote = TRUE, manual = TRUE) # ok
 + [ ]  devtools::check_win_devel() # ok
  + [ ] rhub::check_for_cran() # ok
  + [ ] revdepcheck::revdep_check(num_workers = 4)  # no longer ok but we don't recheck according to the checklist
  + [ ] Update cran-comments.md
  + [ ] git push

Submit to CRAN:

  + [ ] usethis::use_version('patch')
 + [ ]  devtools::submit_cran()
 ```

**Comment by gaborcsardi** [comment]
I think `usethis::use_revdep()` adds it to `.Rbuildignore`. I don't think `revdep_check()` should modify the package.
