### ISSUE TITLE
Resume by default

### ISSUE THREAD

**Issue by hadley** [r-lib/revdepcheck#36]
Currently, if you run `revdep_check()` after a previous partial run, it prompts you to overrwrite or resume. I think it should resume by default, verifying each step to see whether or not it's necessary.

**Comment by gaborcsardi** [comment]
It is pretty hard to know if you need to re-install the local package, that's why `revdep_check` always does it.

**Comment by hadley** [comment]
I think the assumption is that if you're re-running, you don't need to re-install. You don't want to end up in a state where half the checks have been run with one version and half with the other.  I'll add `revdep_reset()` so you can explicitly reset if you want to (that happens implicitly at the end of a successful run)

**Comment by gaborcsardi** [comment]
OK, sounds good.
