### ISSUE TITLE
`cloud_check()` does not check bioconductor by default

### ISSUE THREAD

**Issue by ateucher** [r-lib/revdepcheck#362]
By default `revdepcheck::cloud_check()` does not check bioconductor packages.

From `?cloud_check`: `revdep_packages: A character vector of packages to check, if NULL equal to cran_revdeps()`. And `cran_revdeps()` has the `bioc` argument, which defaults to `FALSE`. Is this the right default for us? Local `revdep_check()` has default `bioc = TRUE`.

(Issue moved from https://github.com/rstudio/revdepcheck-cloud/issues/123)

**Comment by gaborcsardi** [comment]
The cloud check Docker image does not include system dependencies of Bioconductor packages, so there is potential for more failed checks, but other than this, feel free to change the default.

**Comment by ateucher** [comment]
Ok, thanks - that's good to know. It doesn't look like changing the default of `bioc` in `cran_revdeps()` should affect anything else, so I'll make a PR.
