### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by musvaage** [r-lib/revdepcheck#364]
the below if fixed would preferrably accompany a regeneration of the .Rd file

checking

```
$ grep -nr cheking revdepcheck
revdepcheck/R/db.R:57:#' @param package The name of the package under revdep cheking.
revdepcheck/man/db_setup.Rd:10:\item{package}{The name of the package under revdep cheking.}
$ 
```

fix (GNU sed)

```
sed -i "s/cheking/checking/g" R/db.R
```

fix (BSD sed)

```
sed -ie "s/cheking/checking/g" R/db.R
```

plus

regeneration of the relevant .Rd file

**Comment by bbolker** [comment]
Why close this?  As far as I can tell the typo is [still there](https://github.com/r-lib/revdepcheck/blob/main/R/db.R) ?

**Comment by musvaage** [comment]
`https://github.com/r-lib/revdepcheck/issues/364`

`https://github.com/r-lib/rcmdcheck/issues/204`

these ticket's related pulls had numerous test fails

both closed after a length of time as no explanation had been forthcoming regarding the test fails
