### ISSUE TITLE
Test on Linux

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/revdepcheck#45]
In particular, work out how the locally built binary packages should be cached. This is a crancache issue as well.

**Comment by gaborcsardi** [comment]
@krlmlr I think we need this as well:
https://github.com/r-lib/crancache/commit/e0785b54afdeb9ee210915a45030a15ba4a27e9e

Because `revdepcheck` selects the `cran` and `bioc` repos, so we need their locally built binaries as well.

**Comment by krlmlr** [comment]
Thanks. With the most recent changes I could finally revdep-check hms. Now running RSQLite :-)

**Comment by gaborcsardi** [comment]
@krlmlr OK. Let me know if you run into problems.

**Comment by gaborcsardi** [comment]
I think we can close this, because in general it works. Not optimal, but we'll improve that.
