### ISSUE TITLE
Cleanup more

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/revdepcheck#47]
E.g.
* `.tar.gz` source packages
* `vign_test` directories
* all other files, except for `00check.log` and `00install.txt`, maybe?

**Comment by krlmlr** [comment]
Is it safe to remove `revdep/checks/<pkg>/{new,old}/<pkg>.Rcheck/{00_pkg_src,<pkg>}` after a check has completed? When checking RSQLite, I constantly run into space problems, because each package is stored fourfold and e.g. `ChemmineDrugs` has an installed size of just over 9 GB.

**Comment by gaborcsardi** [comment]
YEs, all in `checks` should be safe to remove, although I would need to check the reporting code, because I am not familiar with that.

**Comment by hadley** [comment]
Should we clean up as we go behind each check, rather than waiting until all checks are complete?

Do we also need an explicit (lossy) clean that can be run once you've submitted to CRAN? Or is that just `revdep_reset()`?

**Comment by gaborcsardi** [comment]
IMO: as we go, and just `revdep_reset`.

**Comment by krlmlr** [comment]
I think this is largely fixed in #62.

**Comment by krlmlr** [comment]
...cleaning up "as we go", I mean. We still may clean up more thoroughly.

**Comment by hadley** [comment]
Ah ok, that substantially duplicates `revdep_clean()` so I think we can now remove `revdep_clean()`

**Comment by gaborcsardi** [comment]
I saw you removed `revdep_clean`, and I think we can also close this now.
