### ISSUE TITLE
revdep_install needs to delete pkglib on failure

### ISSUE THREAD

**Issue by hadley** [r-lib/revdepcheck#55]
Ensuring that it either succeeds or fails atomically.  Currently, if it fails, and you re-run `revdep_check()` it will skip the install step.

**Comment by gaborcsardi** [comment]
Yeah, we should probably put the "current" stage in the DB. (After the stage was successful.)

**Comment by hadley** [comment]
Oh yeah, that's a much better approach. I wonder if we should always print each stage, with some special signal if it was completed in a previous run.

**Comment by hadley** [comment]
And my strategy fails to write the report.
