### ISSUE TITLE
Add all results to database

### ISSUE THREAD

**Issue by krlmlr** [r-lib/revdepcheck#58]
`revdep_report_summary()` seems to require access to the `revdep/checks` directory, which I'd rather avoid archiving. Would it be feasible to rely only on the database for displaying summaries?

**Comment by gaborcsardi** [comment]
Yeah, the report should use the db.

**Comment by hadley** [comment]
Related to #47. I'll take a look

**Comment by hadley** [comment]
I'm pretty sure `revdep_report_summary()` only uses what's in the database, and is already run after `revdep_check_clean()` so I'm going to close this. It's possible you had a bad run because of the poor resume algorithm (#55), which I'm fixing at the moment.
