### ISSUE TITLE
first pass 

### ISSUE THREAD

**Issue by bbolker** [r-lib/revdepcheck#64]
*posting this now while waiting for run to finish, will update ...*

running revdepcheck on the `bbmle` package with R version 3.4.0, MacOS, fresh install of revdepcheck/all packages updated
- warning messages (seem harmless but reporting them nonetheless
```
(11x) In rsqlite_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
(3x) In db_results(pkg, revdeps) :
  Some packages were not checked with both versions: ‘metaplus’
```
- I had a few packages fail to install due (I think) to timeouts in the installation process. In this case, we end up with PREPERR in the `status` column of data.sqlite ... and some metadata (version, maintainer) seems to disappear from data.sqlite.. Also, these packages don't show up in the running status report (unlike packages that timeout during checks, which have a "T"). Could this be handled more gracefully?
- might be helpful to remind user where the summaries live (i.e. `revdep/{README,problems.md}` when re-running `revdep_check` with all results cached 
- as far as I can tell (I may be badly mistaken) packages being checked get installed with all of their local packages in a dedicated library, then deleted after checking. I guess this is good for modularity, but it seems **very** expensive to install downstream dependencies many times (separately for every reverse dependency that requires it; e.g. imagine re-installing the entire tidyverse many, many times ... in my case, the `BH` package has been installed at least three times ...).  Is this a simple, justified tradeoff of computation time for simplicity/robustness/modularity? Would it be unreasonable to think of a way that the downstream packages needed could be shared in revdep/library ... ?
- the `revdep_maintainers()` is documented but not exported ...
- document status codes: I=installing, C=checking, D=downloading, I=installing, doubled chars [CC] refer to currently checking against both pkg versions?

**Comment by gaborcsardi** [comment]
> posting this now while waiting for run to finish, will update ...

Please don't update your comment, because I don't get a notification about that. Please make a new comment. Thanks!

> warning messages

harmless and fixed in the github version of `rcmdcheck`

> might be helpful to remind user where the summaries live

Good point.

> it seems very expensive to install downstream dependencies many times 

It is surprisingly cheap, if the binary packages are cached. Which they should be. I just noticed that on 3.4.1 caching does not work, let me fix that: https://github.com/r-lib/crancache/issues/27

> the revdep_maintainers() is documented but not exported

yes, I also want to export some more functions, e.g. `revdep_result` to look over the results quickly. 

> document status codes: I=installing, C=checking, D=downloading, I=installing, doubled chars [CC] refer to currently checking against both pkg versions?

yes, and yes

Thanks!

**Comment by gaborcsardi** [comment]
So when the cache is working properly, it takes about 6s to install the whole tidyverse:
```r
.libPaths("")
unlink("/tmp/library", recursive = TRUE)
dir.create("/tmp/library")
system.time(install_packages("tidyverse", lib = "/tmp/library"))

#> also installing the dependencies ‘colorspace’, ‘mnormt’, ‘bindr’, ‘RColorBrewer’, ‘dichromat’,
#> ‘munsell’, ‘labeling’, ‘rematch’, ‘plyr’, ‘psych’, ‘reshape2’, ‘assertthat’, ‘bindrcpp’, ‘glue’, 
#> ‘pkgconfig’, ‘rlang’, ‘R6’, ‘Rcpp’, ‘BH’, ‘plogr’, ‘digest’, ‘gtable’, ‘scales’, ‘lazyeval’, ‘mime’, 
#> ‘curl’, ‘openssl’, ‘cellranger’, ‘stringi’, ‘selectr’, ‘broom’, ‘dplyr’, ‘forcats’, ‘ggplot2’, ‘haven’,
#> ‘httr’, ‘hms’, ‘jsonlite’, ‘lubridate’, ‘magrittr’, ‘modelr’, ‘purrr’, ‘readr’, ‘readxl’, ‘stringr’, ‘tibble’,
#> ‘rvest’, ‘tidyr’, ‘xml2’
#> 
#> The downloaded binary packages are in
#> 	/var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T//RtmpxsORex/downloaded_packages
#>    user  system elapsed
#>   3.454   2.250   6.086
```

```r
dir("/tmp/library/")
#>  [1] "assertthat"   "BH"           "bindr"        "bindrcpp"     "broom"
#>  [6] "cellranger"   "colorspace"   "curl"         "dichromat"    "digest"
#> [11] "dplyr"        "forcats"      "ggplot2"      "glue"         "gtable"
#> [16] "haven"        "hms"          "httr"         "jsonlite"     "labeling"
#> [21] "lazyeval"     "lubridate"    "magrittr"     "mime"         "mnormt"
#> [26] "modelr"       "munsell"      "openssl"      "pkgconfig"    "plogr"
#> [31] "plyr"         "psych"        "purrr"        "R6"           "RColorBrewer"
#> [36] "Rcpp"         "readr"        "readxl"       "rematch"      "reshape2"
#> [41] "rlang"        "rvest"        "scales"       "selectr"      "stringi"
#> [46] "stringr"      "tibble"       "tidyr"        "tidyverse"    "xml2"
```

**Comment by bbolker** [comment]
OK, some clarification (sorry).

- I actually ran this under Linux (I don't have the appropriate LaTeX tools installed on my Mac, believe it or not). That means that the big time sink is *installing* packages from source, not downloading them. As I understand it what `crancache` saves is the time & bandwidth of *downloading* packages ... ?  If so, then this machinery will be awkward on *nix systems where everything has to be installed from source ...
- now that I've run everything I'm getting some confusing results. What are the rules for reporting problems? Are they only reported if things are OK in the old version and *not* in the new versions? I ask this because the SQL database shows some ERROR outcomes, but there is nothing listed in the problems file (and indeed the ERRORs happen for both old and new bbmle ...). This seems reasonable, but I wonder if it might lead to overlooking problems with the checking procedure ...

**Comment by gaborcsardi** [comment]
> That means that the big time sink is installing packages from source, not downloading them.

It creates binary packages on the fly on these platforms. The process for this is not perfect yet, it will something like this: https://github.com/r-lib/revdepcheck/pull/53#issuecomment-314790995

> but I wonder if it might lead to overlooking problems with the checking procedure

there will be API for listing all errors and you can look at them manually if you want. `revdep_results` and `revdep_details` These are not exported currently.

**Comment by hadley** [comment]
Apart from #70, which I'll work on shortly, I think I've responded to all your issues. Thanks for the detailed feedback!
