### ISSUE TITLE
Use _R_CHECK_SUGGESTS_ONLY_=true in revdep checks

### ISSUE THREAD

**Issue by krlmlr** [r-lib/revdepcheck#66]
because this is what CRAN uses for their incoming checks. Perhaps other switches are also useful (in R-ints just above https://cran.r-project.org/doc/manuals/r-release/R-ints.html#R-coding-standards).

This was a problem with tibble 1.3.0 release.

(Not sure if this even applies to current revdepcheck, moved from https://github.com/hadley/devtools/issues/1438.)

**Comment by gaborcsardi** [comment]
I think in general we want a way to set environment variables for the
workers.

I am not sure what the best default is for `_R_CHECK_SUGGESTS_ONLY_`. Maybe
you are right. But then we also need to (better) notify users about
installation errors.

**Comment by hadley** [comment]
We now have `revdep_env_vars(force_suggests = TRUE)`
