### ISSUE TITLE
High MacOS Finder usage when running revdep_check()

### ISSUE THREAD

**Issue by jimhester** [r-lib/revdepcheck#77]
My Finder window goes a bit crazy with process usage when I am running revdeps with multiple processes. I think because of all the new files created. It would be nice to exclude the `check/` folder from finder. From https://www.tekrevue.com/tip/three-ways-to-prevent-spotlight-from-indexing-items-on-your-mac/ it seems like folders with a `.noindex` extension are not indexed by Spotlight, so this might be a way to do this without having to manually exclude the folders by hand.

**Comment by hadley** [comment]
How do you see this? (i.e. how can I tell if I've fixed the problem)

**Comment by hadley** [comment]
We might also be able to use a [.metadata_never_index](http://www.filetypehelp.com/purpose-files-metadataneverindex-file-extension/) file

**Comment by hadley** [comment]
This seems to list all the files that spotlight is indexing:

```
sudo fs_usage -w -f filesys mdworker | egrep "open"
```

Indexing BH is a nightmare.

**Comment by hadley** [comment]
As far as I can tell, `.metadata_never_index` doesn't prevent spotlight from indexing - even if I force mds to restart.

**Comment by jimhester** [comment]
I was just using Activity monitor, sounds like you found a more quantitative way above.

**Comment by gaborcsardi** [comment]
We use `checks.noindex` and `library.noindex` now on macOS.

**Comment by hadley** [comment]
Can you please an issue in usethis so I remember to update git ignore bits?

**Comment by gaborcsardi** [comment]
Here is a PR: https://github.com/r-lib/usethis/pull/110
