### ISSUE TITLE
troubleshooting lme4 checking on AWS instance

### ISSUE THREAD

**Issue by bbolker** [r-lib/revdepcheck#78]
Context: I'm boldly/foolishly trying to get `revdep_check()` to work for `lme4` on a t2.medium AWS EC2 instance. 

- what does `── E: 0  +1` signify in the progress-bar printout? (in particular, what are the two different values?)
- I'm getting a number of segmentation faults and bad allocation errors (7/22 packages tested so far). (It seems to happen more on the new than the old versions of the packages). Presumably this is because the instance has "only" 4 GiB of memory and I need to upgrade to t2.large ... ? I will also try running with a single worker rather than two workers, once this run finishes.
- several packages are failing to install downstream dependencies, for sometimes non-obvious reasons. 
    - `afex` fails with "Packages required but not available: ‘pbkrtest’ ‘lmerTest’ ‘car’; Package suggested but not available for checking: ‘mlmRev’". I have no idea way, it seems to install fine manually, i.e. via `install.packages("afex")` from within R. Any ideas??   What diagnostics would be helpful? (There are no install logs left around (that I can see): maybe they get cleaned up automatically.)  Maybe there's some kind of race condition happening, because `find .cache/R-crancache | egrep  "pbkrtest|lmerTest|car"` detects the cached packages ... ?
    - `agRee` fails because it depends on `miscF`, which depends on `BRugs`, which needs a working OpenBUGS install. This one is on me (dealing with dependency hell to get OpenBUGS installed on 64-bit Linux), but it would be very useful (wishlist) if there were some way to get info on these problems without manually installing to see where the problem occurs

**Comment by gaborcsardi** [comment]
> what does ── E: 0 +1 signify in the progress-bar printout? (in particular, what are the two different values?)

0 errors with the old version, one new error with the new version. The + ones are the new errors.

> I'm getting a number of segmentation faults and bad allocation errors 

Do you have a swapfile? If not, you probably need one. Segfaults are really strange, though. Can you try with the latest version of the `r-lib/processx` package pls?

> afex fails with "Packages required but not available: ‘pbkrtest’ ‘lmerTest’ ‘car’; Package suggested but not available for checking: ‘mlmRev’". 

The install.out files are in the DB I think, there is just no easy way to see them currently. Sg like this will show it:
```r
det <- revdepcheck:::revdep_details(revdep = "afex")
rcmdcheck::check_details(det$old[[1]])
rcmdcheck::check_details(det$new)
```

We need some API to show this.

> agRee fails because it depends on miscF, which depends on BRugs, which needs a working OpenBUGS install.

Yes, we'll do this, using the system requirements DB.

**Comment by gaborcsardi** [comment]
Btw. you can stop a run with CTRL+C, and then restart it, just run `revdep_check` again, and it will continue.

**Comment by gaborcsardi** [comment]
It would be great to find out where the segfaults are coming from. If you really get a lot of them, could you please try running it with `R -dgdb` and see where the segfault happens? Thanks much!

**Comment by bbolker** [comment]
Thanks for the  quick response!  Since there are another 180 or so packages to check, thought I would just let this one keep running, then tag anything that failed to try again.  I do strongly suspect that the segfaults are somehow a consequence of running out of memory (I know that's not necessarily supported by logic).  I will try re-running after enabling 4G of swap and see whether they recur ...

**Comment by bbolker** [comment]
Huh, still getting some segfaults after boosting swap from 1G (which was already enabled) to 4G.  I'll keep you posted ...

**Comment by bbolker** [comment]
- segfaults may have been from old packages installed in system library?  Tried updating all ...
- any idea what would cause checking to stop with
```
Error: ms is not a length 1 integer
In addition: Warning message:
In FUN(X[[i]], ...) : NAs introduced by coercion to integer range
Execution halted
``` 
?

**Comment by hadley** [comment]
@bbolker one of those processes is the main process (i.e. the one which you called `revdep_check()` from) - it does very little work itself, it's just there to coordinate the other processes. So I don't think you need to worry.

**Comment by hadley** [comment]
I think we've resolved your biggest questions, but please feel free to open smaller issues if there are things we've missed.

**Comment by bbolker** [comment]
thanks! I'll try again.
