### ISSUE TITLE
Showing "E" in progress for all packages

### ISSUE THREAD

**Issue by krlmlr** [r-lib/revdepcheck#81]
on Linux. Looking at `revdep/checks/*/*/*.Rcheck`, the checks seem to succeed though. Just started a fresh run with tibble, didn't have time to investigate yet.

**Comment by krlmlr** [comment]
Trying a second time, no changes. The output looks like this:

```
── CHECK ─────────────────────────────────────────────────────── 208 packages ──
E abjutils                               ── E: ?/?   | W: ?/?   | N: ?/?        
E afmToolkit                             ── E: ?/?   | W: ?/?   | N: ?/?        
E alfred                                 ── E: ?/?   | W: ?/?   | N: ?/?        
E anomalyDetection                       ── E: ?/?   | W: ?/?   | N: ?/?        
E babynames                              ── E: ?/?   | W: ?/?   | N: ?/?        
E antaresViz                             ── E: ?/?   | W: ?/?   | N: ?/?        
```

but the checks seem to finish correctly.

**Comment by gaborcsardi** [comment]
We updated the `rcmdcheck` package, probably that is causing this. I am traveling now, but will try to look at it in the evening.

**Comment by krlmlr** [comment]
Any news? I'd like to revdepcheck dplyr ;-)

**Comment by gaborcsardi** [comment]
Can you pls try an older rcmdcheck commi?

**Comment by krlmlr** [comment]
Can you name a good candidate? I could also try to adapt my existing acceptance tests to revdepcheck and do a bisect.

**Comment by gaborcsardi** [comment]
Away from computer now, but trt before the recent prs.
