### ISSUE TITLE
Clean rebuild

### ISSUE THREAD

**Issue by krlmlr** [r-lib/revdepcheck#85]
when installing the "new" package. I suspect that outdated `.o` files somehow caused bogus failures when revdep-checking dplyr.

**Comment by hadley** [comment]
We're using `crancache::install_packages()` and `remotes::install_local()`. It's possible that remotes isn't building first?

**Comment by hadley** [comment]
I'm going to close because a lot has changed in the package building packages in the last two years, but please feel free to open a new issue if it happens again.
