### ISSUE TITLE
Option to run checks from fastest to slowest

### ISSUE THREAD

**Issue by baptiste** [r-lib/revdepcheck#89]
With a large number of revdeps to check, it could be nice to run them in reverse order of (estimated) time it takes to complete the check, as opposed to alphabetical order. I'm guessing the check time info is available in the CRAN logs.
With this order, one could go through say 90% of the packages in a reasonable time. It's not purely for a psychological benefit (it feels more rewarding), as the decision to run the last few outliers could be made on a case-by-case basis (e.g. switch to a more performant machine, or email the maintainer and ask them to check it themselves, etc.)

Just a thought (while waiting for a list of 288 packages to go down from A to B, then C...).

**Comment by hadley** [comment]
Unfortunately I think the amount of work needed to implement this outweighs the benefit. Why not just (e.g.) set `num_workers = 4` so the check times average out a bit more?

**Comment by baptiste** [comment]
For the record I ran this on my work computer, a 12 core xeon with 64Gb RAM. There's no way I'm doing that again; I can't justify spending so much time on what was essentially a hobby / side-project before it gradually turned into a burden.

**Comment by hadley** [comment]
I run most checks on my quad core laptop; I just let it run overnight.

**Comment by gaborcsardi** [comment]
Yeah, I think on 12 cores you can run 16 checks in parallel, maybe even 24, so 288 packages should be definitely done overnight.

**Comment by gaborcsardi** [comment]
Also, if you want a quick and dirty solution, you can query the check times easily using this API: https://github.com/ropensci/cchecksapi
E.g.: https://cranchecks.info/pkgs/gridExtra and then use `revdep_add` to add the packages that you consider quick enough.

**Comment by baptiste** [comment]
Thanks for the tip Gabor, that's the kind of idea I had in mind.
Might explore this next time, if I don't succumb to the much easier path of
gridExtra2.
