### ISSUE TITLE
Parallel processing: Race conditions between "old" and "new" checks

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/revdepcheck#95]
# Issue
I see inconsistent results when running revdep multiple times (the exact same pkg and revdep pkg versions).  For some runs a package may show an error in "new", sometimes in "old", sometimes in "both", and sometimes in neither.   To resolve this I've found myself doing a `revdep_add(package = redo_pkg)` and restart until both "new" and "old" pass.

I haven't traced the exact reason for this, but an intelligent guess is that some packages request a resources such as a fixed port number that both "new" and "old" try to acquire, i.e. there's a race condition between the two `R CMD check`:s of the same package.

# Suggestion
A possible workaround for race conditions between "new" and "old" is to minimize the risk of them running at the same time.  This could be done by first running "new" for all packages and then "old" for the same packages.   Another way would be to always to "new" and "old" sequentially, with the downside that when testing a small number of packages all cores may not be fully utilized but that should be less of a problem when there's a large number of packages to be tested.

There could of course still be race conditions on shared resources across packages, but the risk for that should be lower than within packages.

**Comment by HenrikBengtsson** [comment]
Here is an example of a test where I think race conditions between "new" and "old" cause revdep checks to fail randomly.  The race condition is because the test tries to to launch a fiery server on fixed port `self$port == 8080`.
```r
> test_check("fiery")
1. Error: life cycle events get fired (@test-Fire.R#168) -----------------------
Failed to create server
1: app$ignite() at testthat/test-Fire.R:168
2: private$run(block = block, showcase = showcase, ...)
3: private$run_blocking_server(showcase = showcase)
4: startServer(self$host, self$port, list(call = private$request_logic, onHeaders = private$header_logic, 
       onWSOpen = private$websocket_logic))
5: stop("Failed to create server")
```

**Comment by HenrikBengtsson** [comment]
When rerunning revdep checks with parallel checks disabled (`num_workers = 1`), these problems appear to go away, which supports my hypothesis on race conditions between "new" and "old".

Here's another test (now by googleComputeEngineR) that looks to have the same race-condition problem:
```r
> test_check("googleComputeEngineR")
1. Error: We can login (@test_aa_auth.R#7) -------------------------------------
Failed to create server
1: expect_is(gce_auth(), "Token2.0") at testthat/test_aa_auth.R:7
2: klass(object)
3: paste(class(x), collapse = "/")
4: gce_auth()
5: googleAuthR::gar_auto_auth(required_scopes, new_user = new_user, no_auto = no_auto, 
       environment_var = "GCE_AUTH_FILE", travis_environment_var = "TRAVIS_GCE_AUTH_FILE")
6: gar_auth(new_user = new_user)
7: httr::oauth2.0_token(endpoint = endpoint, app = app, scope = getOption("googleAuthR.scopes.selected"), 
       cache = getOption("googleAuthR.httr_oauth_cache"))
8: Token2.0$new(app = app, endpoint = endpoint, params = params, credentials = credentials, 
       cache_path = if (is.null(credentials)) cache else FALSE)
9: .subset2(public_bind_env, "initialize")(...)
10: self$init_credentials()
11: init_oauth2.0(self$endpoint, self$app, scope = self$params$scope, user_params = self$params$user_params, 
       type = self$params$type, use_oob = self$params$use_oob, use_basic_auth = self$params$use_basic_auth, 
       config_init = self$params$config_init, client_credentials = self$params$client_credentials)
12: oauth_authorize(authorize_url, use_oob)
13: oauth_listener(url)
14: httpuv::startServer(use$host, use$port, list(call = listen))
15: stop("Failed to create server")
```

**Comment by HenrikBengtsson** [comment]
FYI, being able to avoid running 'old' and 'new' for a specific package at the same time is related to Issue #94 - if that's implemented that same solution could probably be used to run all 'old' first and then all 'new' (called "dev" there).

**Comment by hadley** [comment]
Hmmm, I'm not sure it's within the scope of revdepcheck to solve this. Can you push back to the  package author?

**Comment by krlmlr** [comment]
DBI drivers routinely do this in their checks, but ideally they shouldn't (and use random object names instead).

**Comment by gaborcsardi** [comment]
@krlmlr Or a completely different DB, ideally?

**Comment by schloerke** [comment]
I've run into this with `shiny`.

There's one revdep package that has a port hard coded in its example (`ipc`).  When this example runs in an _old_ check and _new_ check, one of them fails.  If I adjust the `num_workers` to 1, it works fine.

If we could have packages checked in parallel, but not the old/new checked in parallel, that would be great!  

(Then again, this is spot treatment for 1 pkg out of 650)

**Comment by hadley** [comment]
@schloerke I think you should consider that a bug in the package and report it to the maintainer

**Comment by HenrikBengtsson** [comment]
If new and old use parallel::makeCluster() there is always a risk of the two getting the same random port which may cause at the one of them to fail. AFAIK, there's nothing you or the developer can do to avoid this. R pulls a random port from 11000:11999. I don't consider that a bug in the tested package.

Making it less likely that old and new run at the same time will definitely help mitigate this problem.

**Comment by gaborcsardi** [comment]
@HenrikBengtsson that's a bug in the parallel package then.

**Comment by gaborcsardi** [comment]
@HenrikBengtsson I am not sure what you mean by "there's nothing you or the developer can do to avoid this". 

Surely, on every OS, there is a way to bind to an OS-provided random port, by specifying port 0 in bind(2). Also, "a random port from 11000:11999" is not a good idea. If you want a random port, you should let the OS choose, according to its configuration.

**Comment by HenrikBengtsson** [comment]
For my understanding, are you arguing that the 'parallel' package should/could be fixed? That's where the random port is chosen by default.

**Comment by HenrikBengtsson** [comment]
Oh, now I see you previous comment.

**Comment by gaborcsardi** [comment]
I am going to close this.
